### ISSUE TITLE
game bug?

### ISSUE THREAD

**Issue by faizul118** [inotflying/Experimental-UI#1]
so... i was messing with `start_screen.json` today. but was facing a really weird problem. so decided to try your pack to see if the problem is from me or the game and...

![image](https://github.com/user-attachments/assets/cd5f94ff-3991-411a-b8b8-774b37f657dd)

**Comment by AntonyPss** [comment]
hello :D

**Comment by inotflying** [comment]
#BlameMojang
[1.0.1](https://github.com/inotflying/Experimental-UI/commit/86498d969d5ffdaef4ed9f9c8c0e3ae321c75447)
